# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --no-audit --no-fund --prefer-offline
    - run: npm run lint
    - run: npm run build
    - run: sudo npx playwright install-deps
    - run: npm test
    - name: Upload Code Coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: code-coverage
        path: coverage/
        retention-days: 30
    # Commented out since it is outdated and is quite spammy
    # - name: Report code coverage
    #   uses: zgosalvez/github-actions-report-lcov@v2
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     coverage-files: coverage/lcov.info
    #     artifact-name: code-coverage-report
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     working-directory: ./
