# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  push:
    branches:
      - main
      - release/*
      - v*/dev
  pull_request:
    branches:
      - main
      - release/*
      - v*/dev

  # Allows GitHub to use this workflow to validate the merge queue
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_OPTIONS: --max_old_space_size=16384

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci --no-audit --no-fund --prefer-offline
      - run: npm run lint:errors
      - run: npm run build:for:cms
      - run: npm run check:paths
      - run: npm run generate:jsonschema:dist

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci --no-audit --no-fund --prefer-offline
      - run: npx playwright install --with-deps
      - run: npm test
      - name: Upload Code Coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-coverage
          path: coverage/
          retention-days: 30
